### ISSUE TITLE
Don't plot empty bins?

### ISSUE THREAD

**Issue by dstern** [daattali/ggExtra#134] opened 2018-12-19 13:15 UTC
Dean
Love the marginal histogram plots. 
I am plotting data with sparse distributions and would like to plot only bins that contain data. Here's an example
![image](https://user-images.githubusercontent.com/836143/50222244-b1bc5200-0365-11e9-991d-e7a4c7f3e0dd.png)
I am surprised it plots for empty bins, because just plotting with geom_histogram gives the histogram with empty bins not plotted.
![image](https://user-images.githubusercontent.com/836143/50222506-78381680-0366-11e9-86ee-8b1a95b04d3b.png)
Is there an easy, hidden way to not plot bins with missing data in marginal histograms ?
Thanks, David

**Comment by daattali** [comment] 2018-12-19 19:40
Hi David, I'm not quite sure where you see a problem there. Please provide sample input and code to reproduce the issue, and highlight where you see a problem. I'm not sure where in the marginal plots you see empty bins plotted that are not plotted in the geom_histogram, can you please clarify

**Comment by dstern** [comment] 2018-12-19 20:07
Perhaps I was not clear.
The top (blue) histogram contains  the same data as the bottom (gray) histogram. In the blue histogram, bins with 0 counts are plotted as a solid line. I would like to remove this line so that only bins with values are visible. Perhaps this line is not technically a bin? In any case, I would love to be able to remove it.

**Comment by daattali** [comment] 2018-12-19 20:46
Oh I see what you mean. That bottom line is not empty bins, it's just a border line that is always drawn. I don't remember the exact parameters but I don't think you can remove that line without digging into the source code

**Comment by crew102** [comment] 2018-12-19 22:00
Yeah, not possible to remove line without changing source code.

**Comment by dstern** [comment] 2018-12-19 22:41
Thanks. I'll dig into the code and let you know if I come with anything useful.

**Comment by daattali** [comment] 2018-12-19 23:42
You'll definitely be able to remove it by modifying the source code, it's just one (of the many!) theme options that are set. I'm closing this issue because this is not something that is going to change in the package. Feel free to ask for help if you're unable to find the exact option that sets this line

**Closed by daattali** 2018-12-19 23:42 UTC
