### ISSUE TITLE
Histogram margin should be inside of legend

### ISSUE THREAD

**Issue by epruesse** [daattali/ggExtra#60] opened 2017-05-18 01:42 UTC
Minimal example:

```R
library("ggExtra")
# Create some data
set.seed(1234)
x <- c(rnorm(500, mean = -1), rnorm(500, mean = 1.5))
y <- c(rnorm(500, mean = 1), rnorm(500, mean = 1.7))
col <- c(rnorm(500, mean = 1), rnorm(500, mean = 1.3))
df3 <- data.frame(x, y, col)
# Scatter plot of x and y variables and color by groups
sp2 <- ggplot(df3,aes(x, y, color=col)) + geom_point()
ggMarginal(sp2 + theme_gray(), type="histogram")
``` 
![image](https://cloud.githubusercontent.com/assets/2774474/26182902/88d013f0-3b38-11e7-985c-3321f7b7c2eb.png)

The legend and the y-axis histogram should be switched.

**Comment by crew102** [comment] 2017-05-18 01:59
Hi @epruesse  - 

The placement of the legend as it is shown above was actually intentional (i.e., not a bug). The idea was that `ggMarginal` should do its best not to change the scatter plot that the user passes in. If you're not a fan of the legend being placed between the histogram and scatter plot as shown above, you could try moving it to the bottom or left of the scatter plot:

```r
library("ggExtra")
library(ggplot2)
# Create some data
set.seed(1234)
x <- c(rnorm(500, mean = -1), rnorm(500, mean = 1.5))
y <- c(rnorm(500, mean = 1), rnorm(500, mean = 1.7))
col <- c(rnorm(500, mean = 1), rnorm(500, mean = 1.3))
df3 <- data.frame(x, y, col)
# Scatter plot of x and y variables and color by groups
sp2 <- ggplot(df3,aes(x, y, color=col)) + geom_point()
ggMarginal(sp2 + theme_gray() + theme(legend.position = "left"), type="histogram")
```
![rplot01](https://cloud.githubusercontent.com/assets/11220793/26183276/d6f7f616-3b4b-11e7-99f1-8716926047bc.png)

Or you could do `legend.position = "bottom"`

**Closed** 2017-06-13 21:16 UTC
