### ISSUE TITLE
bug in v0.8: ggMarginal with geom_line 

### ISSUE THREAD

**Issue by giuseppec** [daattali/ggExtra#109] opened 2018-04-10 03:34 UTC
I think you introduced a bug:

```r
p = ggplot(mtcars, aes_string(x = "wt", y = "mpg")) + geom_line() + geom_point() 
ggMarginal(p)
# Error in `[.data.frame`(scatDF, , c("var", "fill", "colour", "group")) : 
#   undefined columns selected
```

It used to work in v0.7. Also, switching geom_point() with geom_line() will make it work again.
However, this still seems to be a bug that should be fixed for the next version. 
I guess people already use ggExtra without being aware that the order of `geom_point` and `geom_line` matters. Would be great if you could fix this soon.

```
traceback()
7: stop("undefined columns selected")
6: `[.data.frame`(scatDF, , c("var", "fill", "colour", "group"))
5: scatDF[, c("var", "fill", "colour", "group")]
4: getVarDf(marg = marg, scatPbuilt = scatPbuilt)
3: genRawMargPlot(marg, type = type, scatPbuilt = scatPbuilt, prmL = prmL, 
       groupColour = groupColour, groupFill = groupFill)
2: genFinalMargPlot(marg = "x", type = type, scatPbuilt = scatPbuilt, 
       prmL = prmL, groupColour = groupColour, groupFill = groupFill)
1: ggMarginal(p)
```

**Comment by giuseppec** [comment] 2018-04-10 03:58
I've looked at `scatDF` and basically the `fill` column was missing. 
Maybe you could add some more unit tests for several dataframe preprocessing stuff to avoid such (critical) bugs in the future?

**Comment by daattali** [comment] 2018-04-10 04:29
Thanks for the report - I agree that's a bad bug to introduce! We do make every attempt possible to not introduce any regressions. Every time a bug is found, a unit test is added to ensure similar things won't happen. Will let you know when this is addressed.

**Comment by daattali** [comment] 2018-04-10 19:31
Looks like this is happening because these lines:

https://github.com/daattali/ggExtra/blob/e97e2c01a7b132604e9c23fc1dbdf5a0f05769e4/R/ggMarginal-helpers-genFinalMargPlot.R#L77-L87

don't correctly pick out the geom_point layer. It only looks to see if there is both an x and a y. In the code provided by OP, the `geom_line()` does have x and y, so the code incorrectly treats it as the geom_point just because it's the first layer that has an x and a y.

@crew102

**Comment by daattali** [comment] 2018-04-10 19:40
Perhaps changing the vapply to `scatPbuilt$plot$layers, function(x) class(x$geom)[1] == "GeomPoint"` would solve it

**Comment by crew102** [comment] 2018-04-10 20:40
yeah that's the chunk responsible for the problem. I put together a similar fix last night but found some problems with our tests, so I need to update the test figs/code before opening a pr for this issue.

**Comment by daattali** [comment] 2018-04-17 22:25
this issue can be fixed now

**Closed** 2018-04-20 01:08 UTC

**Comment by VictorNautica** [comment] 2018-11-29 22:10
I got this error too - my plot (which is in a very complex function) looks something like:

`df  %>% ggplot(mapping = aes(x, y)) +
    stat_function(fun = function(x) any_function_here) +
    geom_point()
`

Swapping the stat_function and geom_point calls around fixed it.

**Comment by crew102** [comment] 2018-11-30 15:59
This issue is fixed in the development version of `ggExtra` (see 97e5036dab8b0b19a9291bfbf37b09272f7fba2b). Try installing it with `devtools::install_github("daattali/ggExtra")`.


``` r
library(ggplot2)
library(ggExtra) # dev version

p <- ggplot(mtcars, aes(wt, mpg)) +
  stat_function(fun = exp) +
  geom_point()

ggMarginal(p)
```

![](https://i.imgur.com/eO1X9so.png)

Created on 2018-11-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000).
