### ISSUE TITLE
ggMarginal ignores expand argument

### ISSUE THREAD

**Issue by wpetry** [daattali/ggExtra#145] opened 2019-06-21 18:34 UTC
In `ggMarginal`, the marginal plots use `expand = TRUE` even if the user has specified `p` to have `expand = FALSE`. This leads to a misalignment of the data between the main plot and margins.

**Comment by daattali** [comment] 2019-06-21 20:12
Can you please add a small fully reproducible example code

**Comment by wpetry** [comment] 2019-06-21 20:57
Sure thing, @daattali 

Load packages & generate data
```
library(tidyverse)
library(ggExtra)

theme_set(theme_bw() + theme(panel.grid = element_blank()))

set.seed(503234)
dat <- tibble(x = rbeta(5000, shape1 = 5, shape2 = 1),
              y = exp(rnorm(5000, mean = 0, sd = 2)))
```
Using the default `expand = TRUE` works—the density plots cut off in line with the data. This is expected behavior.
```
p <- ggplot(dat, aes(x = x, y = y))+
  geom_point()+
  scale_y_log10()+
  coord_cartesian(xlim = c(0, 1), expand = TRUE)
ggMarginal(p, type = "density")
```
![Rplot](https://user-images.githubusercontent.com/11151477/59950581-61bd6580-9444-11e9-9fb8-15c2bc387548.jpeg)

Using `expand = FALSE` misaligns the density plots. The lines should extend the whole axis extents, and this is particularly visible in the apparent zero density around `x=1`. This is unexpected behavior.
```
q <- ggplot(dat, aes(x = x, y = y))+
  geom_point()+
  scale_y_log10()+
  coord_cartesian(xlim = c(0, 1), expand = FALSE)
ggMarginal(q, type = "density")
```
![Rplot01](https://user-images.githubusercontent.com/11151477/59950723-be208500-9444-11e9-86dd-ce46d15cd07f.jpeg)

I was able to fix it very crudely by adding a logical argument called `expand` to the function and replacing `top[["coordinates"]][["expand"]] <- expand` and `right[["coordinates"]][["expand"]] <- expand`. This clearly isn't the right way to do it, otherwise I'd send in a PR. Ideally an automated check of the original plot `p` would be run (including custom adjustments, e.g.,  `scale_x_continuous(expand = c(0.5, 1)`), and the top and right marginal plots would be adjusted accordingly.

Thanks for maintaining this great package.

**Comment by daattali** [comment] 2019-06-21 21:04
Great, thanks for the detailed report and examples. I'm on mobile and rushing, but is this related/duplicate of https://github.com/daattali/ggExtra/issues/128 ?

**Comment by wpetry** [comment] 2019-06-21 21:20
They're very closely related for sure (sorry for not referencing #128), but I think this may be a separate (or subset) of that issue that would be easier to fix.

**Comment by daattali** [comment] 2019-06-21 21:41
Thanks for reporting. Feel free to take a look and tackle it in the proper
way if you find some time!

**Comment by wpetry** [comment] 2019-06-22 17:42
I thought I had a solution for the CRAN version, but I see that the GH version has switched to R6. I'm afraid this is a bit out of my depth.

**Comment by crew102** [comment] 2019-06-25 05:06
I'd be happy to integrate your solution into the current codas of ggExtra, so long as the fix you're talking about isn't too hairy.

**Comment by crew102** [comment] 2019-06-29 05:25
Hi @wpetry , I looked into this and it basically amounts to #128. `ggMarginal()` currently doesn't handle the cartesian coordinate system well (i.e., it doesn't work well for plots that were built using the `coord_cartesian()` function). The reason why it seemed like there was a specific issue with the `expand` argument is b/c the `coord_cartesian()` call in your example didn't actually change the look of the plot. If you change the values for `xlim` in your example, you'll see that `ggMarginal()` fails to account for the cartesian coordinate system, even when `expand = TRUE`. In other words, the problem isn't the `expand` argument per se, but rather the inability of `ggMarginal()` to account for `coord_cartesian()`.

``` r
library(ggplot2)
library(ggExtra)

set.seed(503234)
dat <- data.frame(
  x = rbeta(5000, shape1 = 5, shape2 = 1),
  y = exp(rnorm(5000, mean = 0, sd = 2))
)

p <- ggplot(dat, aes(x, y)) +
  geom_point() +
  scale_y_log10() +
  coord_cartesian(xlim = c(0, .5), expand = TRUE)

ggMarginal(p)
```

![](https://i.imgur.com/exrUcRq.png)

Created on 2019-06-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000).

**Comment by daattali** [comment] 2019-06-29 05:34
Thanks for looking into it. Closing this as duplicate

**Closed by daattali** 2019-06-29 05:34 UTC
