### ISSUE TITLE
Marginal histogram bar heights vary depending on color aesthetic / groupFill

### ISSUE THREAD

**Issue by NikKrieger** [daattali/ggExtra#151] opened 2020-04-10 17:53 UTC
I would think that the bar heights in the marginal histograms of the three plots below should all be the same. They should only differ in fill color. 

All three plots use the same underlying data `mtcars`, and I standardized the bin widths across the three plots using the `breaks` parameter.

Notably, this problem is not observed on the [Shiny demo](http://daattali.com/shiny/ggExtra-ggMarginal-demo/)---you can toggle the "Show groups as 'fill'" checkbox, and all the histogram bar heights remain the same.

Is there something I don't know?

``` r
library(magrittr)
library(ggplot2)
library(ggExtra)
ggMarginal(
  ggplot(mtcars, aes(disp, drat, color = factor(cyl))) + geom_point(),
  type = "histogram",
  xparams = list(breaks = seq(90, 500, 10)),
  yparams = list(breaks = seq(2.6, 5, .1))
) %>% plot()
```

![](https://i.imgur.com/BOVSSrB.png)

``` r

ggMarginal(
  ggplot(mtcars, aes(disp, drat, color = factor(cyl))) + geom_point(),
  type = "histogram",
  xparams = list(breaks = seq(90, 500, 10)),
  yparams = list(breaks = seq(2.6, 5, .1)),
  groupFill = TRUE
) %>% plot()
```

![](https://i.imgur.com/I6azFI2.png)

``` r

ggMarginal(
  ggplot(mtcars, aes(disp, drat, color = factor(am))) + geom_point(),
  type = "histogram",
  xparams = list(breaks = seq(90, 500, 10)),
  yparams = list(breaks = seq(2.6, 5, .1)),
  groupFill = TRUE
) %>% plot()
```

![](https://i.imgur.com/Lr2niZw.png)

<sup>Created on 2020-04-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by daattali** [comment] 2020-04-11 04:33
What you're seeing is not because of the colour aesthetic. It's because of the (incorrect? strange?) use of xparams. If you remove the xparams and yparams then the plots will look correct.

xparams and yparams are meant to pass parameters to use for the marginal plots, but passing a `breaks` parameter is not an intended usecase. It's meant more for things like colour or binsize or things like that. The axis itself shouldn't be modified, it should mirror the axis on the main plot.

**Comment by NikKrieger** [comment] 2020-04-11 12:53
I can see that removing the `breaks` parameters corrects the bar heights. The thing is, those parameters are normal `geom_histogram()` parameters--it's another way to specify the bin width, much like the `binwidth` parameter that you alluded to. In other words, these `breaks` are distinct from specifying the axis breaks. Nonetheless, I'll try to find another way to get the bin width and placement that I want.

Nonetheless,

**Comment by daattali** [comment] 2020-04-11 17:17
I looked into this some more and I do still think the problem is because you're effectively changing the axis of the marginal plots by specifying break points that don't match with the min/max of the original plot. For example, min(mtcars$disp) is 71.1 but your breaks start at 90 (and the actual x axis starts a bit before 71.1 because ggplot leaves a small buffer). I'm closing this as I'm fairly certain now that this is not an actual bug, it's working correctly

**Comment by NikKrieger** [comment] 2020-04-13 15:57
It turns out that it's not just a problem with specifying `breaks`---it also occurs when specifying `bins` or `binwidth`:

``` r
library(magrittr)
library(ggplot2)
library(ggExtra)
ggMarginal(
  ggplot(mtcars, aes(disp, drat, color = factor(cyl))) + geom_point(),
  type = "histogram",
  xparams = list(binwidth = 10),
  yparams = list(binwidth = .1)
) %>% plot()
```

![](https://i.imgur.com/p89Cs2N.png)

``` r

ggMarginal(
  ggplot(mtcars, aes(disp, drat, color = factor(cyl))) + geom_point(),
  type = "histogram",
  xparams = list(binwidth = 10),
  yparams = list(binwidth = .1),
  groupFill = TRUE
) %>% plot()
```

![](https://i.imgur.com/z2eLAoL.png)

``` r

ggMarginal(
  ggplot(mtcars, aes(disp, drat, color = factor(am))) + geom_point(),
  type = "histogram",
  xparams = list(binwidth = 10),
  yparams = list(binwidth = .1),
  groupFill = TRUE
) %>% plot()
```

![](https://i.imgur.com/BEpJ3cr.png)

<sup>Created on 2020-04-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It seems that `binwidth` and `bins` also alter the axes of `geom_histograms()`. This can be standardized by standardizing the `limits` parameter in `scale_*_continuous()`:

``` r
library(ggplot2)
plot(
  ggplot(mtcars, aes(disp)) +
    geom_histogram(bins = 30) +
    scale_x_continuous(limits = c(40,450)) +
    theme(axis.text.y = element_blank()) # Added so that axis text doesn't
)                                        # change the width of the plot
#> Warning: Removed 2 rows containing non-finite values (stat_bin).
#> Warning: Removed 2 rows containing missing values (geom_bar).
```

![](https://i.imgur.com/JtYeRuF.png)

``` r
plot(
  ggplot(mtcars, aes(disp)) +
    geom_histogram(binwidth = 17) +
    scale_x_continuous(limits = c(40,450)) +
    theme(axis.text.y = element_blank()) # Added so that axis text doesn't
)                                        # change the width of the plot
#> Warning: Removed 2 rows containing non-finite values (stat_bin).

#> Warning: Removed 2 rows containing missing values (geom_bar).
```

![](https://i.imgur.com/oqsnfg2.png)

``` r
plot(
  ggplot(mtcars, aes(disp)) +
    geom_histogram(breaks = c(117, 203, 333,600)) +
    scale_x_continuous(limits = c(40,450)) +
    theme(axis.text.y = element_blank()) # Added so that axis text doesn't
)                                        # change the width of the plot
#> Warning: Removed 2 rows containing non-finite values (stat_bin).
#> Warning: Removed 1 rows containing missing values (geom_bar).
```

![](https://i.imgur.com/ynNoLCE.png)

<sup>Created on 2020-04-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

But is there a way to do this for `ggMarginal()` plots?

**Comment by daattali** [comment] 2020-04-13 17:05
You're right, it does seem to be off.

After some investigation, it looks like the culprit may be [this line](https://github.com/daattali/ggExtra/blob/b492204d781d1cadb8a74b18e5e4a9264978b345/R/ggMarginal-MarginalPlot.R#L228)

If I change it to `ggplot2::geom_histogram` then it seems to work as expected.

I can trace back the change from `geom_histogram` to `geom_histogram2` in [this commit](https://github.com/daattali/ggExtra/commit/a4654acbfa3f309131fdaccb6ac1aaf426349abf)

@crew102 This is almost 2 years old now, but do you happen to remember why histograms were changed from being plain geom_histogram to being `geom_histogram(ggplot2::aes(y = ..density..)`?

**Comment by daattali** [comment] 2020-04-13 17:14
I think `geom_histogram(ggplot2::aes(y = ..density..)` was added in an effort to support densigram plots, as a way to try to match the histogram bar heights to the density curve height. But I'm not sure why it was needed for regular histogram marginal plots (when densigram isn't used).

**Comment by crew102** [comment] 2020-04-13 17:33
Yep, that' why it was added. I didn't consider the fact that some people would want to be setting params of stat bin that aren't supported by the density stat (e.g., breaks, binwidth). I'll fix sometime this week.

**Comment by daattali** [comment] 2020-06-05 05:38
@NikKrieger can you confirm this is working now as expected? And if it does, please thank @crew102 :)

**Closed** 2020-06-05 05:38 UTC

**Comment by crew102** [comment] 2022-03-02 00:49
Hey @WJH58 , can you provide some sample data so that I can reproduce things on my end? Better yet, can you reproduce issue using a dataset that I would have access to (e.g., built in dataset, or dataset that ships with ggplot).

**Comment by WJH58** [comment] 2022-03-02 07:10
Hi this is my "data2".  
[data2.txt](https://github.com/daattali/ggExtra/files/8167382/data2.txt)

And the code corresponding to the first figure is:  
```
p <- ggplot(data2, aes(x = peptide_length, y = mz, color = factor(charge))) + geom_point() + xlab("Peptide length") + ylab("m.z") + theme_classic() + labs(color='Charge') 
ggMarginal(p, type = "histogram", xparams = list(binwidth = 1))
```
The code corresponding to the second figure is:  
```
p <- ggplot(data2, aes(x = peptide_length, y = mz, color = factor(charge))) + geom_point() + xlab("Peptide length") + ylab("m.z") + theme_classic() + labs(color='Charge') 
ggMarginal(p, type = "histogram", groupFill = TRUE, xparams = list(binwidth = 1))
```

Thanks if you can help!

**Comment by crew102** [comment] 2022-03-02 22:13
Hey @WJH58 , this was actually fixed in https://github.com/daattali/ggExtra/pull/154. If you download the dev version of ggExtra, you should see that the plot looks as expected.

**Comment by WJH58** [comment] 2022-03-03 01:59
@crew102 Thank you! I updated ggExtra and found it worked!

**Comment by daattali** [comment] 2022-03-17 05:57
This reminds me that a new version should go out to CRAN. It will happen within the month.
