### ISSUE TITLE
Histograms axes limits are wrong when using geom_smooth()

### ISSUE THREAD

**Issue by zakahmad** [daattali/ggExtra#9] opened 2015-05-16 20:11 UTC
Occasionally, I like to have both axes of a scatter have the same range or limits (in the original plot below I set the limits to c(-20,30)). However, to demonstrate the issue, I changed the y-axis limits using scale_y_continuous(limits = c(-40,30)) while having scale_x_continuous(limits = c(-20,30)). 

The actual range of the data in the x-axis is: -17.49,  28.56 and on the y-axis is: -9.63, 17.58

I think the location of histograms should adjust and shift when the axes limits are shifted.

![ggextra-issue](https://cloud.githubusercontent.com/assets/5436724/7667762/b18d89b6-fbe4-11e4-9127-d2ad5b6caffd.png)

**Comment by daattali** [comment] 2015-05-16 21:34
I did try to take care of that case, can you provide code to reproduce?

**Comment by daattali** [comment] 2015-05-16 22:15
Thanks for the report. Fixing

**Comment by WilDoane** [comment] 2016-03-08 21:17
A version of this problem appears to still exist when geom_smooth() extends the axis range.

```
gg <-
    ggplot(mtcars, aes(x = mpg, y = cyl)) + 
    geom_point() +
    geom_smooth()
ggMarginal(gg, type = "histogram")

```

![mtcars](https://cloud.githubusercontent.com/assets/550643/13616706/0bdf958c-e549-11e5-8b71-fdb7a8879ba4.png)

```
package       * version date       source        
 colorspace      1.2-6   2015-03-11 CRAN (R 3.2.2)
 devtools        1.10.0  2016-01-23 CRAN (R 3.2.3)
 digest          0.6.9   2016-01-08 CRAN (R 3.2.3)
 ggExtra       * 0.3.1   2015-11-07 CRAN (R 3.2.3)
 ggplot2       * 2.1.0   2016-03-01 CRAN (R 3.2.3)
 gridExtra       2.2.1   2016-02-29 CRAN (R 3.2.3)
 gtable          0.2.0   2016-02-26 CRAN (R 3.2.3)
 labeling        0.3     2014-08-23 CRAN (R 3.2.2)
 memoise         1.0.0   2016-01-29 CRAN (R 3.2.3)
 munsell         0.4.3   2016-02-13 CRAN (R 3.2.3)
 plyr            1.8.3   2015-06-12 CRAN (R 3.2.2)
 Rcpp            0.12.3  2016-01-10 CRAN (R 3.2.3)
 RevoUtilsMath * 3.2.3   2016-02-09 local         
 scales          0.4.0   2016-02-26 CRAN (R 3.2.3)
```

**Comment by daattali** [comment] 2016-03-08 21:50
Thanks for the report. I'm really busy for the next 2 months, I'll try to take a look when I can, but unfortunately this is low priority at the moment

**Comment by daattali** [comment] 2016-04-25 08:38
@WilDoane I looked into this a bit but wasn't able to find a good solution.  What I tried to do is to just copy the scale aesthestics from the main plot to the marginal plot, but for some reason it doesn't work.  If anyone wants to tackle this, I'd gladly welcome a PR.

**Comment by masalmon** [comment] 2016-10-19 12:30
@daattali "What I tried to do is to just copy the scale aesthestics from the main plot" -> where exactly in ggMarginal? Do you mean

```r
        ggplot2::scale_x_continuous(breaks = mean(getLimits(pbTop, "x")),
                                    labels = ylabel)
```
?

I'm looking at the problem because a colleague of mine uses custom x and y limits.

**Comment by daattali** [comment] 2016-10-22 06:10
@masalmon getLimits() and getScale() are two functions I use to try to match the original plot. If your colleague uses custom x and y limits, she should be fine, that works.  Example:

```
ggExtra::ggMarginal(
  ggplot(mtcars, aes(mpg,wt)) +
    geom_point() + 
    scale_x_continuous(limits = c(-5, 60))
)
```

What doesn't work is using `geom_smooth()` - then the y-axis marginal plot is a bit out of place

**Comment by jimoeppen** [comment] 2018-01-11 13:00
The original issue raised by zakahmad in 2015 still seems to be present, without using geom_smooth.  If the default axis limits are over-ridden, the x-axis marginal plot aligns correctly with the data, but the y-axis marginal plot does not.  Here is some code to illustrate the situation [R 3.4.3; ggExtra_0.7; ggplot2_2.2.1]: 

df <- data.frame(x = rnorm(500, 50, 10), y = runif(500, 0, 50))
p1 <- ggplot2::ggplot(df, ggplot2::aes(x, y)) + ggplot2::geom_point() +
  scale_x_continuous(limits = c(0, 150)) +
  scale_y_continuous(limits = c(0, 100))
ggMarginal(p1, type = "histogram")

**Comment by crew102** [comment] 2018-01-11 15:39
@jimoeppen , the problem with using limits with ggMarginal that you mention is related to #81.

**Comment by jimoeppen** [comment] 2018-01-11 16:11
Thank you for the rapid response, and for all the work that goes into ggExtra.

I think #81 implies that setting limits on x affects the y marginal, and vice-versa.  As far as I have seen, the x marginal responds correctly to the x limits.  It is only the y marginal that does not reflect user-specified y axis limits.

Best wishes

Jim Oeppen

Associate Professor
Biodemography Unit
Department of Public Health
University of Southern Denmark (SDU)
J.B. Winsløws Vej 9B
DK-5000  Odense C

Office Phone: +45 6550 9360

**Comment by crew102** [comment] 2018-01-12 01:25
Hi @jimoeppen, both axis are actually problematic. You can see both graphs in #81 for this, or just check out the below code, in which the x marginal plot is wrong and we don't even get a y marginal plot.

```r
library(ggplot2)
library(ggExtra)

p <- ggplot(data = mtcars) +
  geom_point(aes(wt, mpg)) +
  ylim(c(25, 35))

ggMarginal(p, type = "histogram")
```

The bigger issue mentioned in #81 is that ggMarginal is not using the correct range for the marginal plots.

**Comment by jessiepluto** [comment] 2018-02-20 03:34
I just encountered this same issue -- ggMariginal histograms are not lining up with the y-axis correctly after adjusting the limits. Is there any update on a solution?

**Comment by daattali** [comment] 2018-02-20 04:25
A huge feature was just added, the fix for this is next

**Comment by daattali** [comment] 2018-03-28 06:09
fixed

**Closed by daattali** 2018-03-28 06:09 UTC
Labels: help wanted
